title: "Blog of Carlos Sanchez"
description: "Sharing my learnings."
github_username: carlossanlop
twitter_username: foo_fighter
linkedin_url: https://www.linkedin.com/in/carlos-s-3634b228/

markdown: kramdown
markdown_ext: "markdown,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 2
paginate_path: '/:num/'

sass:
    style: :compressed
    sass_dir: assets/css/
